# Production manifest
services:
  mongodb:
    image: mongo:8.0.17-noble
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./database/scripts:/docker-entrypoint-initdb.d:ro

  backend:
    image: ghcr.io/macedonioz/asw-delivery-exam-backend:1.0.0
    container_name: backend
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    restart: on-failure

  frontend:
    image: ghcr.io/macedonioz/asw-delivery-exam-frontend:1.0.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  mongo_data: